name: Run Gradle on PRs
on:
  pull_request:
  push:
      branches: [main]
jobs:
    prBranch:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 11

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Execute Gradle build
              run:  ./gradlew test -PexcludeTests=*.InfoGradleProcessPluginTest
              env:
                GE_URL: ${{ secrets.GE_URL }}
                GE_API_KEY: ${{ secrets.GE_API_KEY }}

    integrationJavaTests:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest]
                version: [11, 17, 19]
                vendor: [temurin, liberica]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Execute Gradle build
              run:  ./gradlew test --tests io.github.cdsap.gradleprocess.InfoGradleProcessPluginTest
